### PR TITLE
bpaf 0.5.0 release

### PR DESCRIPTION
**Pull request by pacak**
Updated to use the new version.

I couldn't test if it works - don't have the binary dependencies this crate uses but it should work.

Please make a ticket if you notice any new issues.

### CODE REVIEW

**Comment by d86leader** [comment]
Thanks! It builds and works fine. I myself would be too lazy to ever update, so thank you for your contribution.

**Comment by d86leader** [comment]
I changed the base branch, can you please fix the conflict in the cargo file? I'm honestly not sure how to do it with github merge requests.

**Comment by pacak** [comment]
>  I'm honestly not sure how to do it with github merge requests.

There's a block where github complains "This branch has conflicts" - it contains a button "Resolve conflicts". If you press that - it opens an editor with both changes visible. Edit the contents, press the "mark as resolved" button.

Feel free to experiment, let me know if you are stuck - I'll to that myself.

**Comment by pacak** [comment]
Updated the branch, also updated bpaf to 0.5.2 - it should start make more meaningful suggestions when you have a typo in your arguments

**Comment by d86leader** [comment]
Thank you for this contribution!

**Pull request merged**
